#!/usr/bin/env bash
# =============================================================================
# Lowkey VPN Client — Quick Start Script
# =============================================================================
#
# Usage:
#   chmod +x client-start.sh
#   ./client-start.sh              # first run: configure, build, login, connect
#   ./client-start.sh --connect    # load saved config and connect immediately
#   ./client-start.sh --build      # rebuild the binary only
#   ./client-start.sh --register   # register a new account
#   ./client-start.sh --status     # show subscription status
#
# Per-machine config is stored in:
#   ~/.config/lowkey/client.env
#
# Session (JWT + server address) is managed by the vpn-client binary itself:
#   ~/.config/lowkey/session.json
# =============================================================================

set -euo pipefail

# ── Colour helpers ─────────────────────────────────────────────────────────────
RED='\033[0;31m'
GRN='\033[0;32m'
YEL='\033[1;33m'
BLU='\033[0;34m'
CYN='\033[0;36m'
RST='\033[0m'

info()    { echo -e "${BLU}[INFO]${RST}  $*"; }
ok()      { echo -e "${GRN}[ OK ]${RST}  $*"; }
warn()    { echo -e "${YEL}[WARN]${RST}  $*"; }
error()   { echo -e "${RED}[ERR ]${RST}  $*" >&2; }
section() { echo -e "\n${CYN}══════════════════════════════════════════${RST}"; \
            echo -e "${CYN}  $*${RST}"; \
            echo -e "${CYN}══════════════════════════════════════════${RST}"; }

# ── Locate script / project root ───────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLIENT_DIR="$SCRIPT_DIR/vpn-client"
BINARY="$CLIENT_DIR/target/release/vpn-client"
CONFIG_DIR="$HOME/.config/lowkey"
ENV_FILE="$CONFIG_DIR/client.env"

# ── Parse CLI flags ────────────────────────────────────────────────────────────
MODE="setup"   # setup | connect | build | register | status
for arg in "$@"; do
    case "$arg" in
        --connect)  MODE="connect"  ;;
        --build)    MODE="build"    ;;
        --register) MODE="register" ;;
        --status)   MODE="status"   ;;
        --help|-h)
            echo "Usage: $0 [--connect|--build|--register|--status]"
            echo ""
            echo "  (no flag)   Full setup: configure, build, login/register, connect"
            echo "  --connect   Load saved config and connect immediately"
            echo "  --build     Rebuild the client binary only"
            echo "  --register  Register a new account (overwrites saved session)"
            echo "  --status    Show current subscription status"
            echo ""
            echo "Config file : $ENV_FILE"
            echo "Session file: $CONFIG_DIR/session.json"
            exit 0 ;;
    esac
done

# =============================================================================
# HELPERS
# =============================================================================

# ── Ensure Rust / cargo is available ──────────────────────────────────────────
ensure_rust() {
    if command -v cargo &>/dev/null; then
        return 0
    fi
    local cargo_bin="$HOME/.cargo/bin/cargo"
    if [[ -x "$cargo_bin" ]]; then
        export PATH="$HOME/.cargo/bin:$PATH"
        return 0
    fi
    info "Installing Rust via rustup..."
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path
    export PATH="$HOME/.cargo/bin:$PATH"
    ok "Rust installed."
}

# ── Build the client binary ───────────────────────────────────────────────────
build_client() {
    section "Building vpn-client (release)"
    ensure_rust
    cd "$CLIENT_DIR"
    info "Running: cargo build --release"
    info "(this may take several minutes on the first run)"
    cargo build --release
    ok "Build complete: $BINARY"
    cd "$SCRIPT_DIR"
}

# ── Load the client config from ~/.config/lowkey/client.env ───────────────────
load_env() {
    if [[ -f "$ENV_FILE" ]]; then
        # Export VAR=VALUE lines, skip comments and blank lines
        set -o allexport
        # shellcheck source=/dev/null
        source "$ENV_FILE"
        set +o allexport
    fi
}

# ── Save the current config to ~/.config/lowkey/client.env ────────────────────
save_env() {
    mkdir -p "$CONFIG_DIR"
    chmod 700 "$CONFIG_DIR"
    cat > "$ENV_FILE" <<EOF
# Lowkey VPN Client — configuration
# Generated by client-start.sh on $(date -u '+%Y-%m-%d %H:%M:%S UTC')

VPN_SERVER="${VPN_SERVER:-}"
VPN_API_PORT="${VPN_API_PORT:-8080}"
VPN_MODE="${VPN_MODE:-tun}"
VPN_SOCKS_PORT="${VPN_SOCKS_PORT:-1080}"
VPN_SPLIT_TUNNEL="${VPN_SPLIT_TUNNEL:-false}"
EOF
    chmod 600 "$ENV_FILE"
    ok "Config written to $ENV_FILE"
}

# ── Interactive first-run configuration ───────────────────────────────────────
setup_config() {
    section "Client configuration"
    mkdir -p "$CONFIG_DIR"

    if [[ -f "$ENV_FILE" ]]; then
        load_env
        warn "Existing config found at $ENV_FILE"
        read -rp "  Overwrite it? [y/N] " OVERWRITE
        if [[ ! "$OVERWRITE" =~ ^[Yy]$ ]]; then
            info "Keeping existing config."
            return 0
        fi
    fi

    echo ""
    echo -e "${YEL}Please answer the following configuration questions.${RST}"
    echo -e "${YEL}Press Enter to accept the default shown in brackets.${RST}"
    echo ""

    # ── Server address (required) ────────────────────────────────────────────
    read -rp "  VPN server address (IP or hostname): " VPN_SERVER
    while [[ -z "$VPN_SERVER" ]]; do
        error "Server address is required."
        read -rp "  VPN server address: " VPN_SERVER
    done

    # ── API port ─────────────────────────────────────────────────────────────
    read -rp "  API port [8080]: " VPN_API_PORT
    VPN_API_PORT="${VPN_API_PORT:-8080}"

    # ── Connection mode ───────────────────────────────────────────────────────
    echo ""
    echo -e "${BLU}Connection mode:${RST}"
    echo "  tun    — routes all traffic through the VPN (Linux/macOS, requires root)"
    echo "  socks5 — runs a local SOCKS5 proxy (all platforms, no root)"
    read -rp "  Mode [tun]: " VPN_MODE
    VPN_MODE="${VPN_MODE:-tun}"
    if [[ "$VPN_MODE" != "tun" && "$VPN_MODE" != "socks5" ]]; then
        warn "Unknown mode '$VPN_MODE', defaulting to tun."
        VPN_MODE="tun"
    fi

    # ── SOCKS5 port (only asked in socks5 mode) ───────────────────────────────
    VPN_SOCKS_PORT="1080"
    if [[ "$VPN_MODE" == "socks5" ]]; then
        read -rp "  Local SOCKS5 listen port [1080]: " VPN_SOCKS_PORT
        VPN_SOCKS_PORT="${VPN_SOCKS_PORT:-1080}"
    fi

    # ── Split tunnel ──────────────────────────────────────────────────────────
    read -rp "  Split tunnel? Only route VPN subnet (10.0.0.0/24), not all traffic [y/N]: " ST
    VPN_SPLIT_TUNNEL="false"
    [[ "$ST" =~ ^[Yy]$ ]] && VPN_SPLIT_TUNNEL="true"

    save_env
}

# ── Register a new account ────────────────────────────────────────────────────
do_register() {
    load_env
    local srv="${VPN_SERVER:-}"
    local port="${VPN_API_PORT:-8080}"

    if [[ -z "$srv" ]]; then
        read -rp "  VPN server address: " srv
    fi

    section "Register new account on $srv"
    read -rp "  Login: " REG_LOGIN
    read -rsp "  Password: " REG_PASS
    echo ""

    "$BINARY" auth register \
        --server "$srv" \
        --api-port "$port" \
        --login "$REG_LOGIN" \
        --password "$REG_PASS"
    ok "Registration complete — session saved."
}

# ── Log in to an existing account ─────────────────────────────────────────────
do_login() {
    load_env
    local srv="${VPN_SERVER:-}"
    local port="${VPN_API_PORT:-8080}"

    if [[ -z "$srv" ]]; then
        read -rp "  VPN server address: " srv
    fi

    section "Log in to $srv"
    read -rp "  Login: " LOGIN_USER
    read -rsp "  Password: " LOGIN_PASS
    echo ""

    "$BINARY" auth login \
        --server "$srv" \
        --api-port "$port" \
        --login "$LOGIN_USER" \
        --password "$LOGIN_PASS"
    ok "Login complete — session saved."
}

# ── Check whether a non-empty JWT session file exists ─────────────────────────
check_session() {
    local session_file="$CONFIG_DIR/session.json"
    [[ -f "$session_file" ]] || return 1

    # Use python3 if available for reliable JSON parsing; fall back to grep
    if command -v python3 &>/dev/null; then
        python3 -c "
import json, sys
try:
    d = json.load(open('$session_file'))
    sys.exit(0 if d.get('token') else 1)
except Exception:
    sys.exit(1)
" 2>/dev/null
    else
        grep -q '"token"[[:space:]]*:[[:space:]]*".\+' "$session_file" 2>/dev/null
    fi
}

# ── Start the VPN connection ──────────────────────────────────────────────────
do_connect() {
    load_env
    local srv="${VPN_SERVER:-}"
    local port="${VPN_API_PORT:-8080}"
    local mode="${VPN_MODE:-tun}"
    local socks="${VPN_SOCKS_PORT:-1080}"
    local split="${VPN_SPLIT_TUNNEL:-false}"

    # Build argument list for vpn-client connect
    local -a conn_args=(
        "--api-port" "$port"
        "--mode"     "$mode"
    )
    [[ -n "$srv"        ]] && conn_args+=("--server" "$srv")
    [[ "$mode" == "socks5" ]] && conn_args+=("--socks-port" "$socks")
    [[ "$split" == "true"  ]] && conn_args+=("--split-tunnel")

    echo ""
    echo -e "${GRN}╔══════════════════════════════════════════════╗${RST}"
    echo -e "${GRN}║       Lowkey VPN Client Connecting           ║${RST}"
    echo -e "${GRN}╠══════════════════════════════════════════════╣${RST}"
    printf "${GRN}║${RST}  Server  : %-33s${GRN}║${RST}\n" "${srv:-<from session>}"
    printf "${GRN}║${RST}  Mode    : %-33s${GRN}║${RST}\n" "$mode"
    if [[ "$mode" == "socks5" ]]; then
    printf "${GRN}║${RST}  SOCKS5  : %-33s${GRN}║${RST}\n" "127.0.0.1:$socks"
    fi
    printf "${GRN}║${RST}  Split   : %-33s${GRN}║${RST}\n" "$split"
    echo -e "${GRN}╠══════════════════════════════════════════════╣${RST}"
    echo -e "${GRN}║${RST}  Ctrl-C to disconnect                        ${GRN}║${RST}"
    echo -e "${GRN}╚══════════════════════════════════════════════╝${RST}"
    echo ""

    # TUN mode needs root; re-exec with sudo if necessary
    if [[ "$mode" == "tun" && $EUID -ne 0 ]]; then
        warn "TUN mode requires root — re-running with sudo..."
        exec sudo -E "$0" --connect
    fi

    "$BINARY" connect "${conn_args[@]}"
}

# =============================================================================
# MAIN
# =============================================================================

# ── Build-only mode ───────────────────────────────────────────────────────────
if [[ "$MODE" == "build" ]]; then
    build_client
    exit 0
fi

# ── Status mode ───────────────────────────────────────────────────────────────
if [[ "$MODE" == "status" ]]; then
    if [[ ! -x "$BINARY" ]]; then
        error "Client binary not found at $BINARY"
        error "Run: $0 --build"
        exit 1
    fi
    load_env
    "$BINARY" subscription status
    exit 0
fi

# ── Auto-build if binary is missing ───────────────────────────────────────────
if [[ ! -x "$BINARY" ]]; then
    warn "Client binary not found — building now..."
    build_client
fi

# ── Register-only mode ────────────────────────────────────────────────────────
if [[ "$MODE" == "register" ]]; then
    do_register
    exit 0
fi

# ── First-run setup ───────────────────────────────────────────────────────────
if [[ "$MODE" == "setup" ]]; then
    setup_config
fi

# ── Ensure we have an active session ─────────────────────────────────────────
section "Authentication"
if check_session; then
    ok "Active session found."
else
    warn "No active session found."
    echo ""
    echo -e "${YEL}Choose an option:${RST}"
    read -rp "  [1] Log in to existing account   [2] Register new account   [q] Quit: " AUTH_CHOICE
    case "$AUTH_CHOICE" in
        1)    do_login    ;;
        2)    do_register ;;
        q|Q)  info "Aborted."; exit 0 ;;
        *)    error "Unknown choice. Aborting."; exit 1 ;;
    esac
fi

# ── Connect ───────────────────────────────────────────────────────────────────
do_connect
